### PR TITLE
Remove deprecated mentions on code

### PR DESCRIPTION
**Pull request by dmcclccam**
Deprecated by #19

### CODE REVIEW

**Comment by Reidmcc** [comment]
@dmcclccam looks good. While you're at it, could you remove the `--iter` flag since it's also deprecated?

**Comment by dmcclccam** [comment]
Sure, done it! ^^

**Comment by Reidmcc** [comment]
thanks! If you'd like a challenge, you can try removing the old code that references those items. You'll want to check `arbitcycle.go`, `arbitrageur/config.go`, `arbitrageur/arbitrageur.go`, and `examples/arbitconfig.cfg`. I'll take care of it tonight otherwise.

**Comment by dmcclccam** [comment]
Well, I tried to do it the "hardcore" way, directly from github's editor. Not a good idea...

**Comment by Reidmcc** [comment]
Hah, yeah, maybe not the best idea. 

We may as well get rid of all of `Start()` in `arbitrageur.go`, it doesn't really work without the cycle iteration concept, and it isn't actually used in the current version. Which would leave just the `iter` flag stuff in `arbitcycle.go`.

**Comment by dmcclccam** [comment]
Well, I will leave that last part on `arbitrageur.go` to you, as I'm pretty sure I'm missing something. 😅

**Comment by Reidmcc** [comment]
@dmcclccam you just deleted an extra `}` at the end of `validateCliParams`, otherwise you had it all right! Thanks for the help, this was on my get-around-to-it-soon list.

**Pull request merged**
